server.port: 8080

spring.cloud.config.enabled: false

eureka.client:
    registerWithEureka: false
    fetchRegistry: false

hazelcast.max.no.heartbeat.seconds: 60

admin-application.url: http://localhost:8080/admin/companies

news-application.url: http://localhost:8080/news/twitter
